### PR TITLE
Fixed omnicite upgrading

### LINKED ISSUE #63: Character ability/coab/skill levels set incorrectly in mana nodes
**Describe the bug**
After using omnicite:

Skill levels can be set to 6 and 7 
image
Coabilities disappear
image
Passives downgrade
image

**On branch**
Develop live 27/12/2022

**To Reproduce**
1. Use omnicite on Summer Verica from 67mc

**Expected behavior**
Skill levels should be 4 and 3
Coabilities should not disappear
Passives should be expected level

**Additional context**
query result of the character from the db: 
```
 DeviceAccountId  | CharaId  | Rarity |   Exp   | Level | AddMaxLevel | HpPlusCount | AtkPlusCount | IsNew | Skill1Lvl | Skill2Lvl | Abil1Lvl | Abil2Lvl | Abil3Lvl | BurstAtkLvl | ComboBuildupCount | HpBase |HpNode | AtkBase | AtkNode | ExAbility1Lvl | ExAbility2Lvl | IsTemp | IsUnlockEditSkill | ManaNodeUnlockCount | ListViewFlag |        GetTime
------------------+----------+--------+---------+-------+-------------+-------------+--------------+-------+-----------+-----------+----------+----------+----------+-------------+-------------------+--------+--------+---------+---------+---------------+---------------+--------+-------------------+---------------------+--------------+------------------------
 REDACTED         | 10850502 |      5 | 8866950 |   100 |          35 |         100 |          100 | t     |         7 |         6 |        6 |        6 |        6 |           4 |                 1 |    578 |   749 |     337 |     444 |             9 |             9 | f      | t                 |                7168 | t            | 2019-11-28 07:07:36+00
```

### PR DESCRIPTION
**Pull request by Nightmerp**
closes #63

### CODE REVIEW

File: DragaliaAPI/Controllers/Dragalia/CharaController.cs [hunk 1]
```diff
@@ -660,7 +683,7 @@ CharaUpgradeMaterialTypes isUseSpecialMaterial
         SortedSet<int> nodes = playerCharData.ManaCirclePieceIdList;
         nodes.AddRange(manaNodes);
 
-        if (nodes.Count == 50)
+        if (nodes.Count >= 50 && manaNodes.Select(x => x <= 50).Any())
```
Comment (SapiensAnatis) [inline DragaliaAPI/Controllers/Dragalia/CharaController.cs:686]:
```suggestion
        if (nodes.Count >= 50 && manaNodes.Any(x => x <= 50))
```

File: DragaliaAPI/Controllers/Dragalia/CharaController.cs [hunk 2]
```diff
@@ -420,35 +420,43 @@ public async Task<DragaliaResult> CharaLimitBreak([FromBody] CharaLimitBreakRequ
...
             playerCharaData,
             usedCurrencies,
             usedMaterials,
             unlockedStories,
             CharaUpgradeMaterialTypes.Omnicite
         );
+
+        if (charaData.HasManaSpiral)
+        {
+            playerCharaData.AdditionalMaxLevel = 20;
```
Comment (SapiensAnatis) [inline DragaliaAPI/Controllers/Dragalia/CharaController.cs:457]: isn't this already modified by CharaManaNodeUnlock?

**Review by SapiensAnatis — COMMENTED** [review]
Will have to test these changes but they look good

File: DragaliaAPI/Controllers/Dragalia/CharaController.cs (hunk 1 above)
Comment (SteelGram) [reply DragaliaAPI/Controllers/Dragalia/CharaController.cs:686]: Could skip iterating through manaNodes again by setting a bool at the end of each iteration in the previous loop over the collection like: is50mcUnlockRelevant = is50mcUnlockRelevant && nodeNr <= 50

Comment (SteelGram) [reply DragaliaAPI/Controllers/Dragalia/CharaController.cs:686]: oops, meant: ...|| nodeNr ...

File: DragaliaAPI/Controllers/Dragalia/CharaController.cs (hunk 2 above)
Comment (Nightmerp) [reply DragaliaAPI/Controllers/Dragalia/CharaController.cs:457]: There isn't really a vanilla way to upgrade both pre-spiral and post-spiral nodes at the same time except for when using omnicite, and CharaManaNodeUnlock doesn't add an additional 5 levels for limit breaking to spiral since it's only in charge of unlocking nodes not limit breaking
I could change it to add 5 to AdditionalMaxLevel in the method if it detects a new 50 mc unlock + spiralled nodes but, idk it made more sense to me to just set it in omnicite upgrading

Comment (SapiensAnatis) [reply DragaliaAPI/Controllers/Dragalia/CharaController.cs:457]: Ah sorry I misread and thought this was += 20 and it would be increased twice. This is fine
